---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: vaultwarden
data:
  vaultwarden.local.lan.conf: |
    server {
      listen *:443 ssl http2;
      server_name vaultwarden.local.lan;
      server_tokens off;

      ssl_certificate /etc/nginx/ssl/cert.pem;
      ssl_certificate_key /etc/nginx/ssl/key.pem;
      ssl on;
      ssl_session_cache builtin:1000 shared:SSL:10m;
      ssl_protocols TLSv1.3;
      access_log /var/log/nginx/nginx.log;

      localtion / {
        proxy_set_header Host $host;
        proxy_set_header X-Real_IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://vaultwarden
      }
    }