---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vaultwarden
  name: vaultwarden
  namespace: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
    spec:
      containers:
      - image: vaultwarden/server:latest
        name: vaultwarden
        env:
        - name: SIGNUPS_ALLOWED
          value: "false"
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: data
          mountPath: "/data"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: vaultwarden

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vaultwarden-backup
  namespace: vaultwarden
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: vaultwarden-backup
            image: alpine:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - "apk update && apk add --no-cache sqlite && sqlite3 /data/db.sqlite3  \"VACUUM INTO '/data-backup/db-$(date '+%Y%m%d-%H%M').sqlite3'\""
            volumeMounts:
            - name: data
              mountPath: "/data"
            - name: data-backup
              mountPath: "/data-backup"
          restartPolicy: OnFailure
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: vaultwarden
          - name: data-backup
            persistentVolumeClaim:
              claimName: vaultwarden-backup