---
 apiVersion: traefik.containo.us/v1alpha1
 kind: IngressRoute
 metadata:
   name: vaultwarden
   namespace: vaultwarden
 spec:
   routes:
   - match: Host(`vaultwarden.local.web`)
     kind: Rule
     services:
     - name: vaultwarden
       port: 80
   tls: {}