---
 apiVersion: traefik.containo.us/v1alpha1
 kind: IngressRoute
 metadata:
   name: vaultwarden
   namespace: vaultwarden
 spec:
   entryPoints:
   - https
   routes:
   - match: Host(`vaultwarden.wcarlsen.dk`)
     kind: Rule
     services:
     - name: vaultwarden
       port: 80
   tls:
     certResolver: default