---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: vaultwarden
spec:
  type: LoadBalancer
  selector:
    app: nginx
  loadBalancerIP: 192.168.1.241
  ports:
  - name: nginx
    port: 443
    targetPort: websecure


---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vaultwarden
