---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  type: LoadBalancer
  selector:
    app: vaultwarden
  loadBalancerIP: 192.168.1.241
  ports:
  - name: vaultwarden
    port: 80
    targetPort: web