---
 apiVersion: traefik.containo.us/v1alpha1
 kind: IngressRoute
 metadata:
   name: jellyfin
   namespace: jellyfin
 spec:
  routes:
  - match: Host(`jellyfin.web.lan`)
    kind: Rule
    services:
    - name: jellyfin
      port: 8096
  tls: {}