---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smokeping
  namespace: smokeping
data:
  Targets: |
    *** Targets ***

    probe = FPing

    menu = Top
    title = Network Latency Grapher
    remark = Welcome to the SmokePing website of WORKS Company. \
            Here you will learn all about the latency of our network.

    + Local
    menu = LAN
    title = LAN

    ++ router
    title = 192.168.1.1
    menu = router
    host = 192.168.1.1

    ++ ISProuter
    title = 10.2.33.1
    menu = ISP router
    host = 10.2.33.1

    + InternetSites
    menu = Internet Sites
    title = Internet Sites
    probe = Curl

    ++ DR
    menu = DR
    title = dr.dk
    host = dr.dk

    ++ TV2
    menu = TV2
    title = tv2.dk
    host = tv2.dk

    ++ GoogleSearch
    menu = Google
    title = google.com
    host = google.com

    ++ Pihole
    menu = Pihole
    title = 192.168.1.240/admin/
    host = 192.168.1.240/admin/

    + DNS
    menu = DNS
    title = DNS

    ++ GoogleDNS1
    menu = Google DNS 1
    title = Google DNS 8.8.8.8
    host = 8.8.8.8

    ++ CloudflareDNS1
    menu = Cloudflare DNS 1
    title = Cloudflare DNS 1.1.1.1
    host = 1.1.1.1

    ++ PiholeDNS
    menu = Pihole DNS
    title = Pihole DNS
    host = 192.168.1.240

    ++ PrimaryDNS
    menu = Primary DNS
    title = Primary DNS
    host = 80.71.128.11

    ++ SecondaryDNS
    menu = Secondary DNS
    title = Secondary DNS
    host = 80.71.128.27

    + DNSProbes
    menu = DNS Probes
    title = DNS Probes
    probe = DNS

    ++ PiholeDNS
    menu = Pihole DNS
    title = Pihole DNS
    host = 192.168.1.240

    ++ PrimaryDNS
    menu = Primary DNS
    title = Primary DNS
    host = 80.71.128.11

    ++ SecondaryDNS
    menu = Secondary DNS
    title = Secondary DNS
    host = 80.71.128.27

    ++ GoogleDNS1
    menu = Google DNS 1
    title = Google DNS 8.8.8.8
    host = 8.8.8.8

    ++ CloudflareDNS1
    menu = Cloudflare DNS 1
    title = Cloudflare DNS 1.1.1.1
    host = 1.1.1.1

  Probes: |
    *** Probes ***

    + FPing
    binary = /usr/sbin/fping

    + DNS
    binary = /usr/bin/dig
    lookup = google.com
    pings = 5
    # step = 300

    +Curl
    binary = /usr/bin/curl
    forks = 5
    offset = 50%
    pings = 5
    # step = 300
    urlformat = http://%host%/ # mandatory
    extraargs = -s