---
 apiVersion: traefik.containo.us/v1alpha1
 kind: IngressRoute
 metadata:
   name: smokeping
   namespace: smokeping
 spec:
   entrypoints:
   - https
   routes:
   - match: Host(`smokeping.local.lan`)
     kind: Rule
     services:
     - name: smokeping
       port: 80
   tls: {}