---
apiVersion: v1
kind: Service
metadata:
  name: smokeping
  namespace: smokeping
spec:
  type: LoadBalancer
  selector:
    app: smokeping
  loadBalancerIP: 192.168.1.243
  ports:
  - name: web
    port: 80
    targetPort: web