---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: traefik
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.5
          args:
            - --log=true
            - --log.level=INFO
            - --accesslog=true
            - --api.insecure
            - --accessLog.format=json
            - --metrics.prometheus
            - --entrypoints.web.Address=:8000
            - --entrypoints.websecure.Address=:4443
            - --providers.kubernetescrd
            - --certificatesresolvers.default.acme.tlschallenge
            - --certificatesresolvers.default.acme.email=carlsenwilli@gmail.com
            - --certificatesresolvers.default.acme.storage=/etc/traefik/acme.json
          ports:
            - name: web
              containerPort: 8000
            - name: websecure
              containerPort: 4443
            - name: admin
              containerPort: 8080
          volumeMounts:
          - name: traefik
            mountPath: /etc/traefik
      volumes:
      - name: traefik
        persistentVolumeClaim:
          claimName: traefik