---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-dns
  namespace: pihole
data:
  custom.list: |
    192.168.1.30 k8s.server.lan
    192.168.1.240 pihole.server.lan
    192.168.1.166 proxmox.server.lan
    192.168.1.167 pivpn.server.lan

  custom-dns.conf: |
    address=/web.lan/192.168.1.242
