---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-dns
  namespace: pihole
data:
  custom.list: |
    192.168.1.30 k8s.lan
    192.168.1.240 pihole.lan
    192.168.1.166 proxmox.lan
    192.168.1.124 server.lan
    192.168.1.242 wcarlsen.dk