---
 apiVersion: traefik.containo.us/v1alpha1
 kind: IngressRoute
 metadata:
   name: pihole
   namespace: pihole
 spec:
   routes:
   - match: Host(`pihole.web.lan`)
     kind: Rule
     services:
     - name: pihole
       port: 80
   tls: {}