apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole
  namespace: pihole
spec:
  encryptedData:
    WEBPASSWORD: AgAEU5sgWCmndC/qf7Xkjz2GFSs3dqGCqj414DQ+bg6ytUvGs9CknXeeshPv87ZbeJ8lXXXr/j32t9W0ciQdW/8r1EOMM1g/X7zcIkvsHoxIRVkXqjAAbLdtjtzO+gnB+cFJpLmB+svTmgVGj2NRE5r6RvDUFJQJgDxfrg2Zlr87BA62BdfRRsN8te1hPOkjWTx6ZhGU5n4TbWtqddHYwQXu39WNQtH8KziLjJGMRfWurTxkOyutdAfYKz5CXhTrIa9cThLHfxbfHF3sgxFzwllKxFb+Fmk7CTyqf8J1SN63Yydjpmc8Y5rZt6BzLcZKkUR1QPYS+w8VtH662iVLcmXUcIx/hvQnrKxRVc7L7MuutIVNEMvVJqs0oPwdL5xTwkbz40dFojh76i6cWG6lv3ES45O896gcT+a3XXRYX0gsPbytAJ6lUSR9SYgjInU1Onz0U82yIFC5cM+efckzftrXGXyuczNYyNm7LxCNBngaCcVuxuBuGIRW2cPUj1qiRSTMddgGtwIKPRXHOevKXnpGAOgPFerF+iN8WQogxKaUai9wXdljfFlZsAjx5kmOOWFV3hKX84zpuewuNNhDile7N7GDxcPoaZBBWP75HM9ZTiCKmpXxhr+e932l0MdZKh6nq460fJZ01TYUhmlC4snimViMDfZcG/uJCFXKWieSwGaznhtZ8jtPZg5LgeJlYi9Ui9j/V5+bQixto4XX
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: pihole
      namespace: pihole

