---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wireguard
  name: wireguard
  namespace: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
      - image: lscr.io/linuxserver/wireguard
        name: wireguard
        env:
        - name: TZ
          value: "Europe/Copenhagen"
        - name: PEERS
          value: "1"
        - name: PEERDNS
          value: "192.168.1.1"
        - name: SERVERPORT
          value: "37"
        - name: ALLOWEDIPS
          valueFrom:
            secretKeyRef:
              name: wireguard
              key: ALLOWEDIPS
        - name: SERVERURL
          valueFrom:
            secretKeyRef:
              name: wireguard
              key: SERVERURL
        - name: INTERNAL_SUBNET
          value: "192.168.1.0"
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
          privileged: true
        ports:
        - containerPort: 37
          protocol: UDP
          name: udp
        volumeMounts:
        - name: config
          mountPath: "/config"
        - name: host
          mountPath: /lib/modules
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: wireguard
      - name: host
        hostPath:
          path: /lib/modules
          type: Directory