---
apiVersion: v1
kind: Service
metadata:
  name: wireguard
  namespace: wireguard
spec:
  type: LoadBalancer
  selector:
    app: wireguard
  loadBalancerIP: 192.168.1.241
  ports:
  - name: wireguard-udp
    protocol: UDP
    port: 43
    targetPort: udp