# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: wireguard
#   namespace: wireguard
# spec:
#   type: LoadBalancer
#   selector:
#     app: wireguard
#   loadBalancerIP: 192.168.1.241
#   ports:
#   - name: wireguard-udp
#     protocol: UDP
#     port: 51820
#     targetPort: 51820
#   # externalTrafficPolicy must be Local to preserve source IP
#   # https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
#   externalTrafficPolicy: Local