apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgCgZAtru+3BFU/7fy33/aF4H9o3nu2DwSiQWHK2yRvtsf/MOxhh4CApcUYI2Ui1ZzXVRfORQeBB/MIW66+/rfY9xp18ellqSC94hegirdG4INB9ojdhLuQIz20wrUBioCySoncP4L42E8ASXKmOWvpeWQ5zZoW+Z/cb4yE0uaj28P19LBgnBgcwYRc2URsHCpKLxSFU0MyP/HQyl0QLWx9Iv2ErqhB5+l3VLzZmQqHZcbd4vT8GMPN12gPX+nEjMBRUmZRh9pJOgJdjm7FpMsCwz0pzFdiKEXMt+WL81Uw4X3h/VpRZ4II0q+P1OrTCykbGQenW4xMLCjlhWsbbGtwE2KavF8u96CCsfhyWsNVm2luJfUU6PHdm7XkLJYKJj+EfVL0otroxCjB063DpBIVEtwgzL9wsxTVMUsa+i6QgTeCnGRTQ1pYldoLwKfUModuNmH+jiozng6vMu0Syl46mmQsT+UtStv5yb2B0yd8p9sksq+6FudLwI4zXQE+LS9N9VjHIYpdZGsMf6lFHdwTlV3Wpn/Shz5rEyjzprQFZvoKt5JJviZ1SgtrktNUF8o6yvELIUP4DKsimMIP0sUvafX/LNXTUX13Tj5sJWGt4xiaiAofgUQ/t3EqP04iFHIqQS5mObbdWGAQpQ6KvHBGzN/cmsSqtOqK1mMGO5FMTyIOqmZzxev2uY7o8JINx4A6t5vujDME2ldKcWeoV
    MINIO_ROOT_USER: AgBFKk+lPhEKMdCl2nPnayQHlvIbW+o1tLfYO5F2a5v4b2iYuP/tsud2yn/7OqYkiQj0v8BowyFcl76wDGHmkm/ERywVMYfBWqamm+yCVYNfYTvq5ha2Zv8Zc5tsvCFcL/3uNs1VFF8BhfmCv8u3HtGFvBXxG01BnlyzKzoRXx6wfwxW/6Iva/gn+Qnr6WGCl79QDSBArIyVog1QZ4jx/+ePsDb/c0zI3XfvN1paDwS+kJReRIaJ5byK0flpdhAUsnGOTW39K4E7pCTM0L0P0h5FwyxfP5b2Jxor9R/+OOCzSPseXaKg/ML0XUiBAEH2s9ldHfg3mZbBDCEpncKp7FE+sfEGzCRXcRB/t6eMdiarn5cQV35lZLpZcs4f9XmXXQ5czPSuNfQz3sLpawmNaV3i/FgHCPM9DYdOtvyB/aF3jyu50DdC1cCrHCPFaFKT9JysAh2YTOFBdNngaJhby8Xt3l7oMHLm3lTHjhAsGQ60SAlVPmlofKwMfBCgve6M6ZHblfhGDkUDgRNltnpQ1btXUeGum3nlLIcylcYW69zTxf6FGX6TCDuZpem1GrT2h68HMvzu46neE2X1G4hTeyMNSJmaZ+/WD7ERxj2HS6lx6fQW0KhlLxDWOvmb2RROXTe2eO4jeCdGkLYhyBgfvnUF/N5f5DyCEhoHeEeDwUu1iPlyvpUi8s0RnDhGJHHHb/jTlmXkQQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: minio
      namespace: minio

