---
 apiVersion: traefik.containo.us/v1alpha1
 kind: IngressRoute
 metadata:
   name: vault
   namespace: vault
 spec:
  routes:
  - match: Host(`vault.web.lan`)
    kind: Rule
    services:
    - name: vault
      port: 8200
  tls: {}