---
 apiVersion: traefik.containo.us/v1alpha1
 kind: IngressRouteTCP
 metadata:
   name: argocd
   namespace: argocd
 spec:
   routes:
   - match: Host(`argocd.web.lan`)
     kind: Rule
     services:
     - name: argocd-server
       port: 443
   tls:
    passthrough: true